
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    container_name: csvsplitter
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
  selenium_chrome:
    image: selenium/standalone-chrome-debug
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - csvsplitter_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/opt/app

volumes:
  csvsplitter_data:
  redis: